nativx_survey/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('survey.urls', namespace='survey')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

survey/urls.py
from django.conf.urls import url
from . import views

app_name = 'survey'

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^finished/$', views.finished, name="finished"),

]

survey/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

survey/forms.py
from django import forms


class ActivityRatingForm(forms.Form):
    RATING_CHOICES = (
        ('0', 'No shot'),
        ('1', 'Probably would not go'),
        ('2', 'Probably would go'),
        ('3', 'Heck yea!')
    )

    rating = forms.ChoiceField(choices=RATING_CHOICES, required=False, label="", label_suffix='')

    def __init__(self, *args, **kwargs):
        label = kwargs.pop('label', "")
        super(ActivityRatingForm, self).__init__(*args, **kwargs)

        if label:
            self.fields['rating'].label = label

    def __str__(self):
        return self.fields['rating'].label


class TextInputForm(forms.Form):
    textInput = forms.CharField(required=False, label="",
                                widget=forms.Textarea(attrs=
                                                      {'rows': 8, 'style': 'width: 100%', 'class': 'form-control',
                                                       'placeholder': 'Custom Text Input'}))

survey/views.py
import json
import re

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext

import forms
import utils
import personality_analyzer
import commit_to_sql


def home(request):
    eat_ratings = utils.get_eat_options(10)
    play_ratings = utils.get_play_options(10)
    text_form = forms.TextInputForm(request.POST or None)
    context = {
        'form': text_form,
        'eat_ratings': eat_ratings,
        'play_ratings': play_ratings,
    }

    if request.method == 'POST':
        if utils.validate_user(request.POST['twitter']) or request.POST['textInput'] is not "":
            eat_data = []
            play_data = []
            for eat_rating in utils.get_all_eat_options():
                eat_element = dict()
                eat_element['activity'] = eat_rating
                request_label = eat_rating + '_eat'
                rating = request.POST.get(request_label, False)
                if not rating:
                    pass
                else:
                    eat_element['rating'] = int(rating)
                    eat_data.append(eat_element)
            for play_rating in utils.get_all_play_options():
                play_element = dict()
                play_element['activity'] = play_rating
                request_label = play_rating + '_play'
                rating = request.POST.get(request_label, False)
                if not rating:
                    pass
                else:
                    play_element['rating'] = int(rating)
                    play_data.append(play_element)
            if request.POST['textInput'] != '':
                text = re.sub(r'[^\x00-\x7F]+', ' ', request.POST.get('textInput', False))
                # Remove non-ASCII
                personality_json = json.dumps(personality_analyzer.run_text(text))
            else:
                personality_json = json.dumps(personality_analyzer.run_twitter(request.POST.get('twitter', False)))
            eat_json = json.dumps(eat_data)
            play_json = json.dumps(play_data)
            commit_to_sql.add_record(personality_json, eat_json, play_json)
            return HttpResponseRedirect(reverse('survey:finished'))
        else:
            return render(request, "home.html", context)

    return render(request, "home.html", context)


def finished(request):
    context = {

    }
    return render(request, "finished.html", context)


def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response


def handler400(request):
    response = render_to_response('400.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 400
    return response

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="NativX survey for data collection on Personality Data vs Travel Preferences">
    <meta name="author" content="David Lance">

    <title>NativX Survey</title>
    <!-- Bootstrap core CSS -->
    <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static "css/navbar-fixed-top.css" %} rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body background={% static "img/background.jpg" %}>

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.nativxtravel.com/">NativX</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href={% url 'survey:home' %}>Survey</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}
    {% endblock %}
</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src={% static 'js/bootstrap.min.js' %}></script>
</body>
</html>

templates/finished.html
{% extends "base.html" %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">NativX Travel Survey</div>
        <div class="panel-body">
            Thank you for completing our survey and helping develop our machine learning algorithm to better plan trips
            in the future. Feel free to take the survey again and continue to help us.<br><br>

            <a class="btn btn-default" href={% url 'survey:home' %}>Back</a>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">NativX Travel Survey</div>
        <div class="panel-body">
            {% if error_message %}
                <div class="alert alert-danger" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
            <p>
                NativX needs your help!
                When you fill this form out, NativX is learning. The more you fill out, the more accurate our
                suggestions are. Help us get the information we need to allow you and other travelers to reach
                adventures that fit. Thanks, you're the best! <br><br>
                Not a huge social media user? All good, you can also put in blog posts or
                papers you wrote, use the custom text input (anything with your own words).<br>
            </p>
            <form action="" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">@</span>
                    <input id="id_twitter" name="twitter" type="text" class="form-control" placeholder="Twitter Handle"
                           aria-describedby="basic-addon1">
                </div>
                <br>
                <div class=" col-lg-12 ">
                    <a class="btn btn-primary" data-toggle="collapse" href="#textEntry" aria-expanded="false"
                       aria-controls="" style="margin-bottom: 20px">
                        Custom Text Option
                    </a>
                    <br>
                </div>
                <div class="collapse" id="textEntry">
                    {{ form.as_p }}
                </div>

                <p>
                    Please selected a rating from 1-4 for each of the respective categories.<br>
                    1: No way (would not go if suggested)<br>
                    2: We'll see (would take some convincing, but might go)<br>
                    3: Why not (would go but could be convince not to go)<br>
                    4: Heck yea (would go if offered)<br>
                </p>

                <div class=" col-lg-6 ">
                    <h1>Eat</h1>
                    <table class="table table-condensed">
                        <thead style="font-weight:bold;">
                        <tr>
                            <td>Activity:</td>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                            <td>4</td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for eat_rating in eat_ratings %}
                            <tr>
                                <td>{{ eat_rating }}</td>
                                <td><input type="radio" name="{{ eat_rating }}_eat" value="1" checked></td>
                                <td><input type="radio" name="{{ eat_rating }}_eat" value="2"></td>
                                <td><input type="radio" name="{{ eat_rating }}_eat" value="3"></td>
                                <td><input type="radio" name="{{ eat_rating }}_eat" value="4"></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class=" col-lg-6 ">
                    <h1>Play</h1>
                    <table class="table table-condensed">
                        <thead style="font-weight:bold;">
                        <tr>
                            <td>Activity:</td>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                            <td>4</td>
                        </tr>
                        </thead>
                        <tbody>
                        {% for play_rating in play_ratings %}
                            <tr>
                                <td>{{ play_rating }}</td>
                                <td><input type="radio" name="{{ play_rating }}_play" value="1" checked></td>
                                <td><input type="radio" name="{{ play_rating }}_play" value="2"></td>
                                <td><input type="radio" name="{{ play_rating }}_play" value="3"></td>
                                <td><input type="radio" name="{{ play_rating }}_play" value="4"></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <input type="submit" value="Submit"/>
            </form>
        </div>
    </div>
{% endblock %}